FD-0.99l

diff --git a/NoExecMe b/NoExecMe
--- a/NoExecMe
+++ b/NoExecMe
@@ -142,23 +142,6 @@ if [ -n "$lib" ]; then
 fi
 
 lib=
-if havelib compat "extern char *re_comp(); re_comp(0)" ctype; then
-	lib=-lcompat
-elif havelib gen "regex_t *re; regfree(re)" "sys/types regex"; then
-	lib=-lgen
-elif havelib PW "regex_t *re; regfree(re)" "sys/types regex"; then
-	lib=-lPW
-elif havelib PW "regex_t *re; regfree(re)" "sys/types regex" "char Error[1024];"
-then
-	lib=-lPW
-	echo "#define	PWNEEDERROR"
-fi
-if [ -n "$lib" ]; then
-	echo "#define	REGEXPLIB	\"$lib\""
-	LIBS="$LIBS $lib"
-fi
-
-lib=
 if noexist "getmntent(0)" "stdio mntent" \
 && havelib sun "getmntent(0)" "stdio mntent"; then
 	lib="$lib -lsun"
@@ -206,8 +189,8 @@ fi
 if noexist errno errno; then
 	echo "#define	NOERRNO"
 fi
-if noinheader '[0-7]+.*,[0-7]+.*,[0-7]+.*' sys/stat "S_IRUSR,S_IWGRP,S_IXOTH"
-then
+if noinheader ' *[0-7]+.*, *[0-7]+.*, *[0-7]+.*' sys/stat \
+"S_IRUSR,S_IWGRP,S_IXOTH"; then
 	echo "#define	NOFILEMODE"
 fi
 if noheader unistd; then
@@ -220,28 +203,30 @@ if noinheader 'struct.*[^a-zA-Z_]fd_set' sys/types \
 && inheader 'struct.*[^a-zA-Z_]fd_set' sys/select; then
 	echo "#define	USESELECTH"
 fi
-if noinheader '0*x*[0-9a-fA-F ]*' sys/param DEV_BSIZE \
-&& inheader '0*x*[0-9a-fA-F ]*' sys/dir DEV_BSIZE; then
+if noinheader ' *0*x*[0-9a-fA-F ]* *' sys/param DEV_BSIZE \
+&& inheader ' *0*x*[0-9a-fA-F ]* *' sys/dir DEV_BSIZE; then
 	echo "#define	USESYSDIRH"
 fi
-if isexist "struct tm *t" "sys/types sys/time time" \
-&& noexist "struct tm *t" "sys/types sys/time"; then
+if inheader "struct.*[^a-zA-Z_]tm[^a-zA-Z_]" "sys/types sys/time time" \
+&& noinheader "struct.*[^a-zA-Z_]tm[^a-zA-Z_]" "sys/types sys/time"; then
 	echo "#define	USETIMEH"
 fi
-if noheader sgtty; then
+if noheader sgtty \
+|| inheader 'TIOCFLUSH' sgtty "TIOCFLUSH"; then
 	echo "#define	USETERMIO"
 fi
 if noheader dirent; then
 	echo "#define	USEDIRECT"
 elif noexist "struct dirent d; d.d_namlen" "sys/types dirent"; then
-	echo "#define	USESYSVDIRENT"
+	echo "#define	SYSVDIRENT"
 fi
 if inheader 'extern.*[^a-zA-Z_]timezone' sys/time \
-&& isexist "extern time_t timezone; timezone" sys/time; then
+&& isexist "extern time_t timezone; timezone" "sys/types sys/time"; then
 	echo "#define	HAVETIMEZONE"
 fi
 
 
+arg=2
 if inheader 'struct.*[^a-zA-Z_]fs_data' sys/mount; then
 	echo "#define	USEFSDATA"
 elif inheader 'struct.*[^a-zA-Z_]statfs' sys/vfs; then
@@ -250,19 +235,18 @@ elif inheader 'struct.*[^a-zA-Z_]statfs' sys/mount; then {
 	echo "#define	USEMOUNTH"
 	if inheader MOUNT_UFS sys/mount; then
 		echo "#define	USEFFSIZE"
-	elif isexist "statfs(0,0,0)" sys/mount; then
-		echo "#define	STATFSARGS	3"
-	fi
+	elif isexist "statfs(0,0,0)" sys/mount; then arg=3; fi
 }
 elif inheader 'struct.*[^a-zA-Z_]statfs' sys/statfs \
-&& isexist "struct statfs f; statfs()" sys/statfs; then {
+&& (isexist "struct statfs f; statfs(0,&f)" sys/statfs \
+|| (isexist "struct statfs f; statfs(0,&f,0,0)" sys/statfs \
+&& arg=4)); then
 	echo "#define	USESTATFSH"
-	if isexist "statfs(0,0,0,0)" sys/statfs; then
-		echo "#define	STATFSARGS	4"
-	fi
-}
 elif inheader 'struct.*[^a-zA-Z_]statvfs' sys/statvfs; then
 	echo "#define	USESTATVFSH"
+fi
+if [ "$arg" != "2" ]; then
+	echo "#define	STATFSARGS	$arg"
 fi
 
 if isexist "getmntent(0)" "stdio mntent"; then
@@ -285,12 +269,25 @@ elif isexist "getfsent()" \
 fi
 
 
-if isexist "extern char *re_comp(); re_comp(0)" ctype; then
+lib=
+if isexist "extern char *re_comp(); re_comp(0)" ctype \
+|| (havelib compat "extern char *re_comp(); re_comp(0)" ctype \
+&& lib=-lcompat); then
 	echo "#define	USERE_COMP"
 elif isexist "regex_t *re; regfree(re)" "sys/types regex"; then
 	echo "#define	USEREGCOMP"
-elif isexist "extern char *regcmp(); regcmp(0,0)" ctype; then
+elif isexist "extern char *regcmp(); regcmp(0,0)" ctype \
+|| (havelib gen "extern char *regcmp(); regcmp(0,0)" ctype \
+&& lib=-lgen) \
+|| (havelib PW "extern char *regcmp(); regcmp(0,0)" ctype \
+&& lib=-lPW) \
+|| (havelib PW "extern char *regcmp(); regcmp(0,0)" ctype "char Error[1024];" \
+&& lib=-lPW && echo "#define	PWNEEDERROR"); then
 	echo "#define	USEREGCMP"
+fi
+if [ -n "$lib" ]; then
+	echo "#define	REGEXPLIB	\"$lib\""
+	LIBS="$LIBS $lib"
 fi
 
 
@@ -300,7 +297,9 @@ fi
 if isexist "setenv(0,0,0)"; then
 	echo "#define	USESETENV"
 fi
-if noexist "select(0,0,0,0,0)"; then
+if noexist "select(0,0,0,0,0)" \
+|| (noinheader 'struct.*[^a-zA-Z_]fd_set' sys/types \
+&& noinheader 'struct.*[^a-zA-Z_]fd_set' sys/select); then
 	echo "#define	NOSELECT"
 fi
 if noexist "strstr(0,0)"; then
